name: Build and Push Wisecow Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u Akilan3585 --password-stdin

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker build -t ghcr.io/akilan3585/wisecow:${SHORT_SHA} .

      - name: Push Docker image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker push ghcr.io/akilan3585/wisecow:${SHORT_SHA}
